### ISSUE TITLE
uhashring in Python 2.7

### ISSUE THREAD

**Issue by rperper** [ultrabug/uhashring#13]
It appears that you use an f string in your programs.  To properly use them in python 2.7 you've got to put a cookie at the top of the file as described in https://pypi.org/project/future-fstrings/

I'm using bmemcached which uses your package in Python 2.7 and I can't install it.  Can you help me with this, or perhaps suggest a workaround.

Thanks!

Bob Perper
rperper@litespeedtech.com

**Comment by ultrabug** [comment]
Hello @rperper 

Which version of uhashring are you using please? 

As [mentioned in the readme](https://github.com/ultrabug/uhashring#python-2-eol) you should be using **version 1.2** if you need to run on Python 2.7.

Hope this helps :)

**Comment by rperper** [comment]
Cool.  I'll see if I can get the customer to that version.

**Comment by ultrabug** [comment]
Also it seems that bmemcached does not specify the uhashring version which is why I guess you get this problem @rperper 

friendly ping @jaysonsantos

**Comment by jaysonsantos** [comment]
Probably it is better if you install with a fixed version o your requirements like
```
bmemcached==x.x.x
uhashring<=1.2
```

**Comment by ultrabug** [comment]
@rperper hi, is that okay for you?

**Comment by ultrabug** [comment]
closing, please reopen if needed mate
