### ISSUE TITLE
The test 'test_distribution' failed sometimes

### ISSUE THREAD

**Issue by huangtianhua** [ultrabug/uhashring#16]
[   37s] =================================== FAILURES ===================================
[   37s] ______________________________ test_distribution _______________________________
[   37s] 
[   37s]     def test_distribution():
[   37s]         ring = HashRing()
[   37s]     
[   37s]         numnodes = 10
[   37s]         numhits = 1000
[   37s]         numvalues = 10000
[   37s]     
[   37s]         for i in range(1, numnodes + 1):
[   37s]             ring["node{}".format(i)] = {"instance": "node_value{}".format(i)}
[   37s]     
[   37s]         distribution = Counter()
[   37s]         for i in range(numhits):
[   37s]             key = str(randint(1, numvalues))
[   37s]             node = ring[key]
[   37s]             distribution[node] += 1
[   37s]     
[   37s]         # count of hits matches what is observed
[   37s]         assert sum(distribution.values()) == numhits
[   37s]     
[   37s]         # usually under 20
[   37s]         standard_dev = _pop_std_dev(distribution.values())
[   37s] >       assert standard_dev <= 20
[   37s] E       assert 21.109239683134017 <= 20
[   37s] 
[   37s] tests/test_distribution.py:39: AssertionError

**Comment by ultrabug** [comment]
Hello

What kind of machine hardware / Python version are you using?

There's nothing I can do without context I'm sorry.

**Comment by ultrabug** [comment]
Yep, thanks mate!
