### ISSUE TITLE
what is the difference between vnode and replica? 

### ISSUE THREAD

**Issue by 1a1a11a** [ultrabug/uhashring#4]
I don't understand the difference between vnode and replica, I thought vnodes are used to make the requests distribute more uniformly, how about replica? Is the same value stored on multiple (number of replica) machines?

**Comment by ultrabug** [comment]
Hello @1a1a11a 

- A replica represents how many times a given key will be placed on the ring for a given node. So this affects the distribution of the keys across the ring.

- A vnode represents how many times the ring will be split between the nodes. If you had only 4 nodes, the ring would be split in 4. vnodes are here to get a more dense distribution of nodes around the ring by virtually inflating their number. This allows to break the range of keys affected when a node is removed or added from/to the ring.

Hope this helps :)
