### ISSUE TITLE
python3 monkey

### ISSUE THREAD

**Issue by garrylachman** [ultrabug/uhashring#5]
The monkey patch not working on python3, the fix is very easy
monkey.py, line 29

> if isinstance(key, types.TupleType):

types.TupleType must be tuple

> if isinstance(key, tuple):

"In Python 2, it contained constants for all primitive types like dict and int. In Python 3, these constants have been eliminated; just use the primitive type name instead."

**Comment by ultrabug** [comment]
Hi @garrylachman thanks a lot for reporting this!

I'm currently in vacation quite far away from home, would you mind submitting a PR for this?

Cheers!

**Comment by ultrabug** [comment]
Thank you so much for reporting and for your patience @garrylachman!

I have updated the tests as well as they should have spotted the issue earlier obviously so this won't happen again :) 

I'm glad to release a new version of uhashring thanks to you!

**Comment by garrylachman** [comment]
:) keep up with your great work
